declare type StepsProps = any;
declare type PositionState = any;
declare type FetchListBody = any;
declare type FetchFormBody = any;
declare type StandardTableActionProps = any;
declare type SimpleFormItemProps = any;
declare type FilterItemProps = any;
declare type LoginPayload = any;
declare module 'md5.js';
declare module 'slang';
